# issuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
  namespace: pfe
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tidiodg1@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - http01:
        ingress:
          name: my-ingress