apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: pfe
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.global-static-ip-name: web-ip
spec:
  tls:
    - secretName: web-ssl
      hosts:
        - www.openmynd.org
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-service
            port:
              number: 10000
      - path: /event
        pathType: ImplementationSpecific
        backend:
          service:
            name: el-github-listener
            port:
              number: 9000
