apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-task-rolebinding
  namespace: pfe
subjects:
- kind: ServiceAccount
  name: default
  namespace: pfe
roleRef:
  kind: Role
  name: tekton-task-role
  apiGroup: rbac.authorization.k8s.io
