apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-test-pods-list-binding
  namespace: pfe
subjects:
- kind: ServiceAccount
  name: tekton-triggers-test
  namespace: pfe
roleRef:
  kind: Role
  name: list-pods-role
  apiGroup: rbac.authorization.k8s.io
