apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-triggers-clusterrole
  namespace: pfe
rules:
- apiGroups: ["triggers.tekton.dev"]
  resources: ["clusterinterceptors"]
  verbs: ["list", "get", "watch"]
