apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend-service
  namespace: pfe
spec:
  ports:
  - name: http
    port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    app: frontend
  type: NodePort