apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
  namespace: pfe
  labels:
    app: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot-container
        image: "tidix/public:chatbot-v1.0"
        ports:
        - containerPort: 11000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: my-api-key
              key: OPENAI_API_KEY