apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatbot
  name: chatbot-service
  namespace: pfe
spec:
  ports:
  - name: http
    port: 11000
    protocol: TCP
    targetPort: 11000
  selector:
    app: chatbot
  type: NodePort