apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend-service
  namespace: pfe
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: backend
  type: NodePort