apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: pfe
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: "tidix/public:frontend"
        ports:
        - containerPort: 10000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: my-api-key
              key: OPENAI_API_KEY